-- MySQL Script generated by MySQL Workbench
-- Sun Oct 26 19:25:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fabrica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fabrica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fabrica` DEFAULT CHARACTER SET utf8 ;
USE `fabrica` ;

-- -----------------------------------------------------
-- Table `fabrica`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`pessoa` (
  `idpessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(65) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `idpessoa_UNIQUE` (`idpessoa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`pessoa_juridica` (
  `pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `insc_est` VARCHAR(15) NOT NULL,
  `nome_fantasia` VARCHAR(45) NULL,
  PRIMARY KEY (`pessoa_idpessoa`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_juridica_pessoa`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `fabrica`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`pessoa_fisica` (
  `pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `sexo` ENUM('M', 'F') NULL,
  PRIMARY KEY (`pessoa_idpessoa`),
  CONSTRAINT `fk_pessoa_fisica_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `fabrica`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(64) NULL,
  `pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  INDEX `fk_usuario_pessoa1_idx` (`pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `fabrica`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`contato` (
  `pessoa_fisica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `pessoa_juridica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `status` ENUM('ativo', 'inativo') NULL,
  PRIMARY KEY (`pessoa_fisica_pessoa_idpessoa`, `pessoa_juridica_pessoa_idpessoa`),
  INDEX `fk_pessoa_fisica_has_pessoa_juridica_pessoa_juridica1_idx` (`pessoa_juridica_pessoa_idpessoa` ASC) VISIBLE,
  INDEX `fk_pessoa_fisica_has_pessoa_juridica_pessoa_fisica1_idx` (`pessoa_fisica_pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_fisica_has_pessoa_juridica_pessoa_fisica1`
    FOREIGN KEY (`pessoa_fisica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`pessoa_fisica` (`pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_fisica_has_pessoa_juridica_pessoa_juridica1`
    FOREIGN KEY (`pessoa_juridica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`pessoa_juridica` (`pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`empressa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`empressa` (
  `pessoa_juridica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pessoa_juridica_pessoa_idpessoa`),
  CONSTRAINT `fk_empressa_pessoa_juridica1`
    FOREIGN KEY (`pessoa_juridica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`pessoa_juridica` (`pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`cliente` (
  `empressa_pessoa_juridica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`empressa_pessoa_juridica_pessoa_idpessoa`),
  CONSTRAINT `fk_cliente_empressa1`
    FOREIGN KEY (`empressa_pessoa_juridica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`empressa` (`pessoa_juridica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`fornecedor` (
  `empressa_pessoa_juridica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`empressa_pessoa_juridica_pessoa_idpessoa`),
  CONSTRAINT `fk_fornecedor_empressa1`
    FOREIGN KEY (`empressa_pessoa_juridica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`empressa` (`pessoa_juridica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`insumo` (
  `idinsumo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `unidade` ENUM('un', 'lt', 'kg') NULL,
  PRIMARY KEY (`idinsumo`),
  UNIQUE INDEX `idinsumo_UNIQUE` (`idinsumo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`funcionario` (
  `pessoa_fisica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`pessoa_fisica_pessoa_idpessoa`),
  CONSTRAINT `fk_funcionario_pessoa_fisica1`
    FOREIGN KEY (`pessoa_fisica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`pessoa_fisica` (`pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`comprador` (
  `funcionario_pessoa_fisica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`funcionario_pessoa_fisica_pessoa_idpessoa`),
  CONSTRAINT `fk_comprador_funcionario1`
    FOREIGN KEY (`funcionario_pessoa_fisica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`funcionario` (`pessoa_fisica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`pedido_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`pedido_compra` (
  `idpedido_compra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `fornecedor_empressa_pessoa_juridica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `comprador_funcionario_pessoa_fisica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpedido_compra`),
  UNIQUE INDEX `idpedido_compra_UNIQUE` (`idpedido_compra` ASC) VISIBLE,
  INDEX `fk_pedido_compra_fornecedor1_idx` (`fornecedor_empressa_pessoa_juridica_pessoa_idpessoa` ASC) VISIBLE,
  INDEX `fk_pedido_compra_comprador1_idx` (`comprador_funcionario_pessoa_fisica_pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_compra_fornecedor1`
    FOREIGN KEY (`fornecedor_empressa_pessoa_juridica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`fornecedor` (`empressa_pessoa_juridica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_compra_comprador1`
    FOREIGN KEY (`comprador_funcionario_pessoa_fisica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`comprador` (`funcionario_pessoa_fisica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`insumo_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`insumo_pedido` (
  `insumo_idinsumo` INT UNSIGNED NOT NULL,
  `pedido_compra_idpedido_compra` INT UNSIGNED NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`insumo_idinsumo`, `pedido_compra_idpedido_compra`),
  INDEX `fk_insumo_has_pedido_compra_pedido_compra1_idx` (`pedido_compra_idpedido_compra` ASC) VISIBLE,
  INDEX `fk_insumo_has_pedido_compra_insumo1_idx` (`insumo_idinsumo` ASC) VISIBLE,
  CONSTRAINT `fk_insumo_has_pedido_compra_insumo1`
    FOREIGN KEY (`insumo_idinsumo`)
    REFERENCES `fabrica`.`insumo` (`idinsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumo_has_pedido_compra_pedido_compra1`
    FOREIGN KEY (`pedido_compra_idpedido_compra`)
    REFERENCES `fabrica`.`pedido_compra` (`idpedido_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`vendedor` (
  `metar` DOUBLE NOT NULL,
  `funcionario_pessoa_fisica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`funcionario_pessoa_fisica_pessoa_idpessoa`),
  CONSTRAINT `fk_vendedor_funcionario1`
    FOREIGN KEY (`funcionario_pessoa_fisica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`funcionario` (`pessoa_fisica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`pedido` (
  `idpedido` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `cliente_empressa_pessoa_juridica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  `vendedor_funcionario_pessoa_fisica_pessoa_idpessoa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpedido`),
  UNIQUE INDEX `idpedido_UNIQUE` (`idpedido` ASC) VISIBLE,
  INDEX `fk_pedido_cliente1_idx` (`cliente_empressa_pessoa_juridica_pessoa_idpessoa` ASC) VISIBLE,
  INDEX `fk_pedido_vendedor1_idx` (`vendedor_funcionario_pessoa_fisica_pessoa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_empressa_pessoa_juridica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`cliente` (`empressa_pessoa_juridica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_vendedor1`
    FOREIGN KEY (`vendedor_funcionario_pessoa_fisica_pessoa_idpessoa`)
    REFERENCES `fabrica`.`vendedor` (`funcionario_pessoa_fisica_pessoa_idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`produto` (
  `idproduto` INT UNSIGNED NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `unidade` ENUM('un', 'lt', 'kg') NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`produto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`produto_pedido` (
  `produto_idproduto` INT UNSIGNED NOT NULL,
  `pedido_idpedido` INT UNSIGNED NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`produto_idproduto`, `pedido_idpedido`),
  INDEX `fk_produto_has_pedido_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  INDEX `fk_produto_has_pedido_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_pedido_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `fabrica`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `fabrica`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fabrica`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fabrica`.`lote` (
  `idlote` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `produto_idproduto` INT UNSIGNED NOT NULL,
  `pedido_idpedido` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idlote`),
  UNIQUE INDEX `idlote_UNIQUE` (`idlote` ASC) VISIBLE,
  INDEX `fk_lote_produto1_idx` (`produto_idproduto` ASC) VISIBLE,
  INDEX `fk_lote_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_lote_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `fabrica`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `fabrica`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;